<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_156791</name>
   <tag></tag>
   <elementGuidId>9e5de4b7-6522-4512-81c0-83e869489bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/table/tbody/tr[3]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;156791đ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>77d441d8-3cbe-427e-b543-d2d1069bd124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2</value>
      <webElementGuid>61496260-1039-449f-b5da-005bdf57e925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>156791đ</value>
      <webElementGuid>92652ae6-8000-4720-9554-95ceba56f95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen transition duration-300 bg-white text-black&quot;]/div[@class=&quot;min-h-screen bg-white text-black&quot;]/div[@class=&quot;container mx-auto p-4&quot;]/div[@class=&quot;flex flex-col lg:flex-row gap-6&quot;]/div[@class=&quot;lg:w-96 lg:sticky lg:top-4 lg:self-start&quot;]/div[@class=&quot;bg-gray-50 rounded-lg shadow-lg p-4&quot;]/div[@class=&quot;cart p-6 rounded-lg shadow-md w-full max-w-md mx-auto transition duration-300
      bg-gray-100 text-black&quot;]/div[1]/table[@class=&quot;min-w-full table-auto&quot;]/tbody[1]/tr[@class=&quot;border-b border-gray-200&quot;]/td[@class=&quot;py-2&quot;]</value>
      <webElementGuid>b6f73cff-d099-4d8a-adce-30287f42f92e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/table/tbody/tr[3]/td[3]</value>
      <webElementGuid>c2119773-b9ce-4651-88b1-39d6e2178d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chocolate Chip Cookies'])[2]/following::td[2]</value>
      <webElementGuid>959c9ef9-4b6c-4cd2-af83-5025f8ae91c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vegetarian Stir-Fry'])[2]/following::td[5]</value>
      <webElementGuid>e6b849b7-0314-4576-bf5d-e1e52b577de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chicken Alfredo Pasta'])[2]/preceding::td[1]</value>
      <webElementGuid>ac554ba1-c8f6-4156-8358-21a62ed6d269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mango Salsa Chicken'])[2]/preceding::td[4]</value>
      <webElementGuid>3e05b14a-79b3-47f2-b024-35584c02ea35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='156791']/parent::*</value>
      <webElementGuid>ff87233a-4ac2-46b2-b588-c8d2dd29b3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]</value>
      <webElementGuid>1051106c-49db-4064-a57d-d55b740e9c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '156791đ' or . = '156791đ')]</value>
      <webElementGuid>1b03bc91-c1b1-4c67-ad2f-3a2b0baf33ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
