<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_200788</name>
   <tag></tag>
   <elementGuidId>a36f611c-8779-4de5-90eb-54a72c021315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;200788đ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>aa3f0c59-06b3-4ce4-a621-1df9f2f631ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2</value>
      <webElementGuid>24d6b768-6cbe-4b2d-b0b2-9950cf51c3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>200788đ</value>
      <webElementGuid>22aec1a3-66a6-46a6-86bd-2d75ee733ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen transition duration-300 bg-white text-black&quot;]/div[@class=&quot;min-h-screen bg-white text-black&quot;]/div[@class=&quot;container mx-auto p-4&quot;]/div[@class=&quot;flex flex-col lg:flex-row gap-6&quot;]/div[@class=&quot;lg:w-96 lg:sticky lg:top-4 lg:self-start&quot;]/div[@class=&quot;bg-gray-50 rounded-lg shadow-lg p-4&quot;]/div[@class=&quot;cart p-6 rounded-lg shadow-md w-full max-w-md mx-auto transition duration-300
      bg-gray-100 text-black&quot;]/div[1]/table[@class=&quot;min-w-full table-auto&quot;]/tbody[1]/tr[@class=&quot;border-b border-gray-200&quot;]/td[@class=&quot;py-2&quot;]</value>
      <webElementGuid>352de809-5936-45c9-b437-d52dbe8bd4fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/table/tbody/tr/td[3]</value>
      <webElementGuid>d97b37a9-edd6-45ad-9bb0-e127ec4e9138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classic Margherita Pizza'])[2]/following::td[2]</value>
      <webElementGuid>1ebed583-cd77-43fd-bb39-1e106916e76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price'])[1]/following::td[3]</value>
      <webElementGuid>a220d247-14b4-4be4-9f9e-07408365c8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vegetarian Stir-Fry'])[2]/preceding::td[1]</value>
      <webElementGuid>7cdfa69e-338f-415c-ba78-02d33aecb782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chocolate Chip Cookies'])[2]/preceding::td[4]</value>
      <webElementGuid>546125ae-705a-4fdd-8742-bcb07d22f6e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='200788']/parent::*</value>
      <webElementGuid>165e7bc4-bf81-42f0-931e-2b91280d6fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>daf58654-15c2-49f3-bd94-bdb3e729a4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '200788đ' or . = '200788đ')]</value>
      <webElementGuid>ae68cc17-3e0c-47ba-8a3a-f22c37229bf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
