<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_249073</name>
   <tag></tag>
   <elementGuidId>881c1342-08ed-4d1b-a9d4-5fe56dec5a46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/table/tbody/tr[5]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;249073đ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>68f3d978-eebe-4865-8ae0-7f001dd2c4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2</value>
      <webElementGuid>dcceb459-e0dd-4668-87b9-9230f6b61af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>249073đ</value>
      <webElementGuid>58732d9e-6624-4e5b-9f32-a1e2b32211b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen transition duration-300 bg-white text-black&quot;]/div[@class=&quot;min-h-screen bg-white text-black&quot;]/div[@class=&quot;container mx-auto p-4&quot;]/div[@class=&quot;flex flex-col lg:flex-row gap-6&quot;]/div[@class=&quot;lg:w-96 lg:sticky lg:top-4 lg:self-start&quot;]/div[@class=&quot;bg-gray-50 rounded-lg shadow-lg p-4&quot;]/div[@class=&quot;cart p-6 rounded-lg shadow-md w-full max-w-md mx-auto transition duration-300
      bg-gray-100 text-black&quot;]/div[1]/table[@class=&quot;min-w-full table-auto&quot;]/tbody[1]/tr[@class=&quot;border-b border-gray-200&quot;]/td[@class=&quot;py-2&quot;]</value>
      <webElementGuid>2ad11fe5-633e-405c-b1bf-ef12293c3826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div[2]/div/table/tbody/tr[5]/td[3]</value>
      <webElementGuid>d4a03df9-0ea1-4b5f-93f9-9b851f270ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mango Salsa Chicken'])[2]/following::td[2]</value>
      <webElementGuid>ab566731-88a5-418f-82ca-7c27aa994b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chicken Alfredo Pasta'])[2]/following::td[5]</value>
      <webElementGuid>3dd65fc1-959b-4496-8ad6-e61c11cd720f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quinoa Salad with Avocado'])[2]/preceding::td[1]</value>
      <webElementGuid>54b0a0cf-7e2f-4777-89de-960ee2a99f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='249073']/parent::*</value>
      <webElementGuid>4c4635c6-909c-4252-9a95-89266182e01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]</value>
      <webElementGuid>557dc9ae-3e8b-43c7-8d52-f6a222bec8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '249073đ' or . = '249073đ')]</value>
      <webElementGuid>798c98d0-63e3-40f0-9458-ad6d739e56d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
